import type {
  Pod,
  Person,
  WorkItem,
  Allocation,
  TimeOff,
  Scenario,
} from '../types';

// ---- Pods ----
export const seedPods: Pod[] = [
  { id: 'pod-ww', name: 'Word Wizards' },
  { id: 'pod-ps', name: 'Pod Squad' },
  { id: 'pod-tp', name: 'TINPOZ' },
  { id: 'pod-ss', name: 'ServerScapes' },
  { id: 'pod-la', name: 'Lalo' },
  { id: 'pod-qa', name: 'QA Pool' },
];

// ---- People ----
export const seedPeople: Person[] = [
  // Internal leads
  {
    id: 'person-emily',
    name: 'Emily',
    role: 'qa_lead',
    type: 'internal',
    weeklyCapacityDays: 5,
    status: 'active',
  },
  {
    id: 'person-izzy',
    name: 'Izzy',
    role: 'pod_lead',
    homePodId: 'pod-ps',
    type: 'internal',
    weeklyCapacityDays: 5,
    status: 'active',
    defaultPodFilterIds: ['pod-ps'],
  },
  {
    id: 'person-lionel',
    name: 'Lionel',
    role: 'pod_lead',
    homePodId: 'pod-la',
    type: 'internal',
    weeklyCapacityDays: 5,
    status: 'active',
    defaultPodFilterIds: ['pod-la'],
  },
  {
    id: 'person-kawika',
    name: 'Kawika',
    role: 'pod_lead',
    homePodId: 'pod-tp',
    type: 'internal',
    weeklyCapacityDays: 5,
    status: 'active',
    defaultPodFilterIds: ['pod-tp', 'pod-ss'],
  },
  {
    id: 'person-tbh',
    name: 'TBH',
    role: 'pod_lead',
    homePodId: 'pod-ww',
    type: 'internal',
    weeklyCapacityDays: 5,
    status: 'active',
    defaultPodFilterIds: ['pod-ww'],
  },

  // ---- LALO pod vendors ----
  { id: 'person-thanush', name: 'Thanush', role: 'tester', homePodId: 'pod-la', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-lionel' },
  { id: 'person-ajith', name: 'Ajith', role: 'tester', homePodId: 'pod-la', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-lionel' },
  { id: 'person-madiki-uday', name: 'Madiki Uday', role: 'tester', homePodId: 'pod-la', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-lionel' },
  { id: 'person-lokeswar-reddy', name: 'Lokeswar Reddy', role: 'tester', homePodId: 'pod-la', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-lionel' },
  { id: 'person-manikanta', name: 'Manikanta Varma Datla', role: 'tester', homePodId: 'pod-la', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-lionel' },
  { id: 'person-akhila', name: 'Akhila M S', role: 'tester', homePodId: 'pod-la', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-lionel' },
  { id: 'person-vishweshwar', name: 'Vishweshwar R', role: 'tester', homePodId: 'pod-la', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-lionel' },

  // ---- Word Wizards pod vendors ----
  { id: 'person-ram-prasath', name: 'Ram Prasath S', role: 'tester', homePodId: 'pod-ww', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-tbh' },
  { id: 'person-sabarinathan', name: 'Sabarinathan', role: 'tester', homePodId: 'pod-ww', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-tbh' },
  { id: 'person-abhishek', name: 'Abhishek R', role: 'tester', homePodId: 'pod-ww', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-tbh' },
  { id: 'person-siranjeevi', name: 'Siranjeevi', role: 'tester', homePodId: 'pod-ww', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-tbh' },
  { id: 'person-mukesh', name: 'Mukesh M', role: 'tester', homePodId: 'pod-ww', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-tbh' },

  // ---- Pod Squad pod vendors ----
  { id: 'person-shreekantacharya', name: 'Shreekantacharya', role: 'tester', homePodId: 'pod-ps', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-izzy' },
  { id: 'person-jayanth', name: 'Jayanth R', role: 'tester', homePodId: 'pod-ps', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-izzy' },
  { id: 'person-gagan', name: 'Gagan B L', role: 'tester', homePodId: 'pod-ps', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-izzy' },
  { id: 'person-sudeep', name: 'Sudeep M', role: 'tester', homePodId: 'pod-ps', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-izzy' },
  { id: 'person-gowtham', name: 'Gowtham', role: 'tester', homePodId: 'pod-ps', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-izzy' },

  // ---- TINPOZ pod vendors ----
  { id: 'person-mithun', name: 'Mithun', role: 'tester', homePodId: 'pod-tp', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-kawika' },
  { id: 'person-sai-ram', name: 'Sai Ram', role: 'tester', homePodId: 'pod-tp', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-kawika' },
  { id: 'person-sathish', name: 'Sathish V', role: 'tester', homePodId: 'pod-tp', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-kawika' },
  { id: 'person-momin', name: 'Momin', role: 'tester', homePodId: 'pod-tp', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-kawika' },
  { id: 'person-srivalli', name: 'Srivalli', role: 'tester', homePodId: 'pod-tp', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-kawika' },
  { id: 'person-shiva-kiran', name: 'Shiva Kiran', role: 'tester', homePodId: 'pod-tp', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-kawika' },
  { id: 'person-srujan', name: 'Srujan', role: 'tester', homePodId: 'pod-tp', type: 'vendor', weeklyCapacityDays: 5, status: 'active', leadId: 'person-kawika' },
];

// ---- Work Items ----
// Based on Wordscapes Release Overview spreadsheet
// Jira base URL: https://peoplefun.atlassian.net/browse/

export function generateSeedWorkItems(): WorkItem[] {
  return [
    // ============================================================
    // 3.10 Release (3/18 → 3/23) — Regression: 3/9-3/23
    // ============================================================

    // Major features
    {
      id: 'wi-310-curated-ftue',
      type: 'feature',
      name: 'Daily Puzzle: Curated FTUE',
      podId: 'pod-ps',
      startDate: '2026-01-23',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 3,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-33450',
      notes: '3.10 Release — Major feature. Producer: Daniella.',
    },
    {
      id: 'wi-310-remote-content',
      type: 'feature',
      name: 'Remote Content Delivery',
      podId: 'pod-ww',
      startDate: '2026-02-02',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 3,
      releaseDate: '2026-03-23',
      notes: '3.10 Release — Major feature. Producer: Matt.',
    },

    // Minor features
    {
      id: 'wi-310-ui-consistency',
      type: 'feature',
      name: 'UI Consistency Pass: Mt Fortune',
      podId: 'pod-ps',
      startDate: '2026-01-28',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-33606',
      notes: '3.10 Release — Minor feature. Producer: Daniella.',
    },
    {
      id: 'wi-310-help-request-overhaul',
      type: 'feature',
      name: '[Chat Improvements] Help Request Overhaul',
      podId: 'pod-tp',
      startDate: '2026-01-30',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 3,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-34670',
      notes: '3.10 Release — Minor feature. Producer: Matt.',
    },
    {
      id: 'wi-310-chronicle-announcements',
      type: 'feature',
      name: 'Chronicle Support for Announcements',
      podId: 'pod-tp',
      startDate: '2026-01-26',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-35411',
      notes: '3.10 Release — Minor feature. Producer: Matt.',
    },
    {
      id: 'wi-310-chronicle-offers',
      type: 'feature',
      name: 'Chronicle Support for Offers',
      podId: 'pod-la',
      startDate: '2026-02-17',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-36045',
      notes: '3.10 Release — Minor feature. Producer: Casey.',
    },

    // Platform / SDK
    {
      id: 'wi-310-pt-core-ads',
      type: 'initiative',
      name: 'PT Core 3.0.0 & PT Ads 1.1.1 Updates',
      podId: 'pod-qa',
      startDate: '2026-02-13',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-36066',
      notes: '3.10 Release — Platform. Producer: Casey.',
    },
    {
      id: 'wi-310-helpshift-reports',
      type: 'initiative',
      name: 'Update Helpshift CS reports (ad network + CRID)',
      podId: 'pod-qa',
      startDate: '2026-01-22',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-31618',
      notes: '3.10 Release — Platform. Producer: Casey.',
    },
    {
      id: 'wi-310-adjust-sdk',
      type: 'initiative',
      name: 'Adjust SDK Update for 3.10.0',
      podId: 'pod-qa',
      startDate: '2026-01-21',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-34770',
      notes: '3.10 Release — SDK update. Producer: Casey.',
    },

    // ABTs
    {
      id: 'wi-310-fast-play-abt',
      type: 'feature',
      name: 'Fast Play ABT',
      podId: 'pod-ww',
      startDate: '2026-02-23',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-36196',
      notes: '3.10 Release — ABT. Producer: Matt.',
    },
    {
      id: 'wi-310-store-badging-abt',
      type: 'feature',
      name: 'LiveOps ABTs: Store badging audit',
      podId: 'pod-la',
      startDate: '2026-01-21',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-32338',
      notes: '3.10 Release — ABT. Producer: Casey.',
    },
    {
      id: 'wi-310-mountain-climb-abt',
      type: 'feature',
      name: 'Mountain Climb Rewards ABT',
      podId: 'pod-ps',
      startDate: '2026-01-27',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-33489',
      notes: '3.10 Release — ABT. Producer: Casey.',
    },

    // Bug-fixing
    {
      id: 'wi-310-offer-group-type',
      type: 'feature',
      name: 'Create new offer group type for low priority announcements',
      podId: 'pod-la',
      startDate: '2026-02-27',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-03-23',
      jiraKey: 'WSU-36687',
      notes: '3.10 Release — Bug-fixing. Producer: Daniella.',
    },

    // LiveOps (3.10)
    {
      id: 'wi-310-easter-liveops',
      type: 'feature',
      name: 'Easter LiveOps (Mar 30)',
      podId: 'pod-ww',
      startDate: '2026-02-03',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-03-23',
      notes: '3.10 Release — LiveOps. Event goes live Mar 30. Producer: Casey.',
    },
    {
      id: 'wi-310-april-fools',
      type: 'feature',
      name: 'April Fools LiveOps (Apr 1)',
      podId: 'pod-ps',
      startDate: '2026-02-04',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-03-23',
      notes: '3.10 Release — LiveOps. Event goes live Apr 1. Producer: Casey.',
    },
    {
      id: 'wi-310-inflatable-man-pet',
      type: 'feature',
      name: 'Wacky Inflatable Man Engagement Pet (Apr 1)',
      podId: 'pod-la',
      startDate: '2026-02-12',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-03-23',
      notes: '3.10 Release — LiveOps. Event goes live Apr 1. Producer: Casey.',
    },
    {
      id: 'wi-310-q2-mt-fortune',
      type: 'feature',
      name: 'Q2 Mt. Fortune (Underwater) (Apr 1)',
      podId: 'pod-tp',
      startDate: '2026-02-12',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-03-23',
      notes: '3.10 Release — LiveOps. Event goes live Apr 1. Producer: Casey.',
    },
    {
      id: 'wi-310-earth-day',
      type: 'feature',
      name: 'Earth Day LiveOps (Apr 12)',
      podId: 'pod-tp',
      startDate: '2026-02-04',
      endDate: '2026-03-23',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-03-23',
      notes: '3.10 Release — LiveOps. Event goes live Apr 12. Producer: Casey.',
    },

    // ============================================================
    // 3.9.2 Release (TBD) — Hotfix
    // ============================================================
    {
      id: 'wi-392-d2c-appcharge',
      type: 'feature',
      name: '[D2C][Shop][AppCharge] IAP rewards missing on hard close',
      podId: 'pod-la',
      startDate: '2026-03-03',
      endDate: '2026-03-14',
      requiredMinDaysPerWeek: 3,
      jiraKey: 'WSU-37051',
      notes: '3.9.2 Hotfix — Bug-fixing. Producer: Daniella.',
    },

    // ============================================================
    // 3.11 Release (4/14) — Merge: 3/27, Code Freeze: 3/30
    // ============================================================
    {
      id: 'wi-311-team-remove-revamp',
      type: 'feature',
      name: 'TeamRemove Revamp - Ghost players & redis cleanup',
      podId: 'pod-ss',
      startDate: '2026-03-16',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 3,
      releaseDate: '2026-04-14',
      jiraKey: 'WSU-35850',
      notes: '3.11 Release — Minor feature. In Dev. Producer: Matt.',
    },
    {
      id: 'wi-311-tiered-no-ads-abt',
      type: 'feature',
      name: 'Tiered No Ads x New Players ABT',
      podId: 'pod-la',
      startDate: '2026-03-06',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-04-14',
      notes: '3.11 Release — Minor feature. In Dev. Producer: Daniella.',
    },
    {
      id: 'wi-311-chat-qol',
      type: 'feature',
      name: 'Chat QOL Fixes & Improvements - Join/Kick/Remove',
      podId: 'pod-tp',
      startDate: '2026-03-13',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-04-14',
      jiraKey: 'WSU-35846',
      notes: '3.11 Release — Minor feature. Pre-Pro. Producer: Matt.',
    },
    {
      id: 'wi-311-att-opt-in',
      type: 'feature',
      name: 'ATT Opt-in Redesign',
      podId: 'pod-ps',
      startDate: '2026-03-11',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-04-14',
      jiraKey: 'WSU-35048',
      notes: '3.11 Release — Minor feature. In Dev. Producer: Matt.',
    },
    {
      id: 'wi-311-daily-gift-theming',
      type: 'feature',
      name: 'Daily Gift Theming & Simplified Daily Gift Widget',
      podId: 'pod-ww',
      startDate: '2026-03-06',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-04-14',
      jiraKey: 'WSU-32344',
      notes: '3.11 Release — Minor feature. In Dev. Producer: Casey.',
    },
    {
      id: 'wi-311-pt-core-ads',
      type: 'initiative',
      name: 'PT Core & PT Ads Updates for 3.11.0',
      podId: 'pod-qa',
      startDate: '2026-03-20',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-04-14',
      jiraKey: 'WSU-36897',
      notes: '3.11 Release — Platform. Pre-Pro. Producer: Casey.',
    },
    {
      id: 'wi-311-mothers-day',
      type: 'feature',
      name: 'Mother\'s Day LiveOps (May 4)',
      podId: 'pod-ps',
      startDate: '2026-03-06',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-04-14',
      notes: '3.11 Release — LiveOps. In QA. Producer: Casey.',
    },
    {
      id: 'wi-311-picnic-day',
      type: 'feature',
      name: 'Picnic Day LiveOps (May 17)',
      podId: 'pod-ww',
      startDate: '2026-03-06',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-04-14',
      notes: '3.11 Release — LiveOps. In QA. Producer: Casey.',
    },
    {
      id: 'wi-311-summer-sand-castle',
      type: 'feature',
      name: '[Summer] Sand Castle Crowns (Jun 1)',
      podId: 'pod-la',
      startDate: '2026-03-05',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-04-14',
      notes: '3.11 Release — LiveOps. In QA. Producer: Casey.',
    },
    {
      id: 'wi-311-summer-daily-goals',
      type: 'feature',
      name: 'Summer 1-3 Daily Goals with Michael\'s Tooling (Jun 1)',
      podId: 'pod-tp',
      startDate: '2026-03-06',
      endDate: '2026-04-14',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-04-14',
      notes: '3.11 Release — LiveOps. In QA. Producer: Casey.',
    },

    // ============================================================
    // 3.12 Release (5/12) — Merge: 4/24, Code Freeze: 4/27
    // ============================================================
    {
      id: 'wi-312-wildlife-levels',
      type: 'feature',
      name: 'Wildlife Level Expansion',
      podId: 'pod-ww',
      startDate: '2026-04-14',
      endDate: '2026-05-12',
      requiredMinDaysPerWeek: 3,
      releaseDate: '2026-05-12',
      notes: '3.12 Release — Major feature. In Dev. At risk. Producer: Casey.',
    },
    {
      id: 'wi-312-pt-core-ads',
      type: 'initiative',
      name: 'PT Core and PT Ads Updates for 3.12.0',
      podId: 'pod-qa',
      startDate: '2026-04-20',
      endDate: '2026-05-12',
      requiredMinDaysPerWeek: 2,
      releaseDate: '2026-05-12',
      notes: '3.12 Release — Platform. Pre-Pro. Producer: Casey.',
    },
    {
      id: 'wi-312-9th-wordscapes-day',
      type: 'feature',
      name: '9th Wordscapes Day LiveOps',
      podId: 'pod-ps',
      startDate: '2026-04-14',
      endDate: '2026-05-12',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-05-12',
      notes: '3.12 Release — LiveOps. Pre-Pro. Producer: Casey.',
    },
    {
      id: 'wi-312-cow-pet',
      type: 'feature',
      name: 'Cow Engagement Pet',
      podId: 'pod-la',
      startDate: '2026-04-14',
      endDate: '2026-05-12',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-05-12',
      notes: '3.12 Release — LiveOps. Pre-Pro. Producer: Casey.',
    },
    {
      id: 'wi-312-fathers-day',
      type: 'feature',
      name: 'Father\'s Day LiveOps',
      podId: 'pod-tp',
      startDate: '2026-04-14',
      endDate: '2026-05-12',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-05-12',
      notes: '3.12 Release — LiveOps. Pre-Pro. Producer: Casey.',
    },
    {
      id: 'wi-312-independence-day',
      type: 'feature',
      name: 'Independence Day LiveOps',
      podId: 'pod-ww',
      startDate: '2026-04-14',
      endDate: '2026-05-12',
      requiredMinDaysPerWeek: 1,
      releaseDate: '2026-05-12',
      notes: '3.12 Release — LiveOps. Pre-Pro. Producer: Casey.',
    },

    // ============================================================
    // Server Release 76.0.0 (TBD) — Feature Freeze: 2/24
    // ============================================================
    {
      id: 'wi-srv76-text-limit',
      type: 'feature',
      name: '[SERVER] Validate text limit on text field',
      podId: 'pod-ss',
      startDate: '2026-02-24',
      endDate: '2026-03-13',
      requiredMinDaysPerWeek: 1,
      jiraKey: 'WSU-36174',
      notes: 'Server Release 76.0.0 — Done. Producer: Alec.',
    },
    {
      id: 'wi-srv76-d2c-award',
      type: 'feature',
      name: 'D2C doesn\'t grant award on dev environment',
      podId: 'pod-ss',
      startDate: '2026-02-24',
      endDate: '2026-03-13',
      requiredMinDaysPerWeek: 2,
      jiraKey: 'WSU-37065',
      notes: 'Server Release 76.0.0 — In QA. At risk. Producer: Alec.',
    },
    {
      id: 'wi-srv76-persistent-help',
      type: 'feature',
      name: 'Investigate persistent help request issue',
      podId: 'pod-ss',
      startDate: '2026-02-24',
      endDate: '2026-03-13',
      requiredMinDaysPerWeek: 2,
      jiraKey: 'WSU-37048',
      notes: 'Server Release 76.0.0 — In QA. At risk. Producer: Alec.',
    },
    {
      id: 'wi-srv76-help-request-overhaul',
      type: 'feature',
      name: '[Chat Improvements] Help Request Overhaul (Server)',
      podId: 'pod-ss',
      startDate: '2026-02-24',
      endDate: '2026-03-13',
      requiredMinDaysPerWeek: 2,
      jiraKey: 'WSU-34670',
      notes: 'Server Release 76.0.0 — In QA. At risk. Producer: Alec.',
    },
    {
      id: 'wi-srv76-help-unit-tests',
      type: 'feature',
      name: 'Help improvements - Unit and Integration Tests',
      podId: 'pod-ss',
      startDate: '2026-02-24',
      endDate: '2026-03-13',
      requiredMinDaysPerWeek: 1,
      jiraKey: 'WSU-35492',
      notes: 'Server Release 76.0.0 — Done. Producer: Alec.',
    },
    {
      id: 'wi-srv76-announcements',
      type: 'feature',
      name: 'Implement Ability to display an Announcement',
      podId: 'pod-ss',
      startDate: '2026-02-24',
      endDate: '2026-03-13',
      requiredMinDaysPerWeek: 1,
      jiraKey: 'WSU-35358',
      notes: 'Server Release 76.0.0 — Done. Producer: Alec.',
    },
  ];
}

// No auto-generated allocations — team will plan manually
export function generateSeedAllocations(_workItems: WorkItem[]): Allocation[] {
  return [];
}

// No auto-generated time offs — team will add their own
export function generateSeedTimeOffs(): TimeOff[] {
  return [];
}

export const basePlanScenario: Scenario = {
  id: 'scenario-base',
  name: 'Base Plan',
  isBase: true,
};

/** Fixed realm ID for the shared team planning data (Dexie Cloud) */
export const TEAM_REALM_ID = 'rlm-team-planning';

/** Team member emails to auto-invite to the shared realm */
export const TEAM_EMAILS = [
  'emily.mccormick@peoplefun.com',
  'peter.yiap@peoplefun.com',
  'adam.brzozowski@peoplefun.com',
  'casey.takesue@peoplefun.com',
  'daniella.eguiguren@peoplefun.com',
  'nichole.strano@peoplefun.com',
  'alec.bautista@peoplefun.com',
];
